# Generated by Django 3.2 on 2021-04-25 01:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cactusApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
