# Generated by Django 3.2 on 2021-04-25 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cactusApp', '0004_measurement_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='bmi',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='measurement',
            name='date',
            field=models.DateField(),
        ),
    ]
