# Generated by Django 3.2 on 2021-04-26 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cactusApp', '0005_auto_20210425_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.ImageField(upload_to='charts')),
                ('bmi', models.ImageField(upload_to='charts')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cactusApp.child')),
            ],
        ),
    ]
